routes/web.php
<?php

use App\Http\Controllers\VoterController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {


    // Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', 'ElectionController@index')->name('home');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::put('/profile', 'ProfileController@update')->name('profile.update');

    // Route::post('/voters/import', 'VoterController@import')->name('voters.import');
    // Route::resource('voters', 'VoterController');

    Route::resource('elections', 'ElectionController');

    // Candidate
    Route::get('/elections/{election}/candidates/', 'CandidateController@index')->name('candidates.index');
    Route::post('/elections/{election}/candidates/', 'CandidateController@store')->name('candidates.store');
    Route::get('/elections/{election}/candidates/create', 'CandidateController@create')->name('candidates.create');
    Route::get('/elections/{election}/candidates/{candidate}', 'CandidateController@edit')->name('candidates.edit');
    Route::put('/elections/{election}/candidates/{candidate}', 'CandidateController@update')->name('candidates.update');
    Route::put('/elections/{election}/candidates-image/{candidate}', 'CandidateController@update_image')->name('candidates.update_image');
    Route::delete('/elections/{election}/candidates/{candidate}', 'CandidateController@destroy')->name('candidates.delete');

    // Voter
    Route::get('/elections/{election}/voters/', 'VoterController@index')->name('voters.index');
    Route::post('/elections/{election}/voters/', 'VoterController@store')->name('voters.store');
    Route::get('/elections/{election}/voters/create', 'VoterController@create')->name('voters.create');
    Route::get('/elections/{election}/voters/{voter}', 'VoterController@edit')->name('voters.edit');
    Route::put('/elections/{election}/voters/{voter}', 'VoterController@update')->name('voters.update');
    Route::delete('/elections/{election}/voters/{voter}', 'VoterController@destroy')->name('voters.destroy');
    Route::post('/elections/{election}/voters/import', 'VoterController@import')->name('voters.import');

    Route::get('/about', function () {
        return view('about');
    })->name('about');
});

app/Election.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Election extends Model
{
    use HasFactory,SoftDeletes;
    protected $guarded = [];

     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'start_at', 'end_at'
    ];
}

app/Http/Controllers/API/ElectionController.php
<?php

namespace App\Http\Controllers\API;

use App\Election;
use App\Http\Controllers\Controller;
use App\Http\Resources\ElectionResource;
use Validator;
use Illuminate\Http\Request;

class ElectionController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Election::latest()->get();

        return response()->json([ElectionResource::collection($data)]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $election = Election::find($id);
        if (is_null($election)) {
            return response()->json('Data not found', 404); 
        }
        return response()->json([new ElectionResource($election)]);
    }

}

app/Http/Controllers/ElectionController.php
<?php


namespace App\Http\Controllers;

use App\Election;
use App\User;

use Illuminate\Http\Request;

class ElectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::count();
        $elections = Election::all();
        // $widget = [
        //     'users' => $users,            
        //     'elections' => $elections,
        //     //...
        // ];
        // dd($elections);
        return view('election/index', compact('elections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $users = User::count();

        $widget = [
            'users' => $users,
            //...
        ];

        return view('election/create', compact('widget'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());

        $this->validate($request,[
            'election_name' => 'required',
            'election_start_at' => 'required|date|before:election_end_at',
            'election_end_at' => 'required|date|after:election_start_at'
        ]);

        $election = new Election();

        $election->name = $request->election_name;
        $election->start_at = $request->election_start_at;
        $election->end_at = $request->election_end_at;
        $election->save();

        return redirect(route('elections.index'))->with('success','Election Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Election  $election
     * @return \Illuminate\Http\Response
     */
    public function show(Election $election)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Election  $election
     * @return \Illuminate\Http\Response
     */
    public function edit(Election $election)
    {
        //
        $users = User::count();
        // $election_detail = Election::find($election);
        $data = [
            'users' => $users,
            'election' => $election,
            //...
        ];

        return view('election/edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Election  $election
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Election $election)
    {
        //
        // dd($request->input());
        $this->validate($request,[
            'election_name' => 'required',
            'election_start_at' => 'required|date|before:election_end_at',
            'election_end_at' => 'required|date|after:election_start_at'
        ]);

        $election->update(
            [
                'name'=> $request->election_name,
                // 'start_at'=> $request->election_start_at,
                'start_at'=> date('Y-m-d H:i', strtotime($request->election_start_at)),
                'end_at'=> date('Y-m-d H:i', strtotime($request->election_end_at)),
            ]
        );
        return redirect(route('elections.index'))->with('success','Election Successfully Updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Election  $election
     * @return \Illuminate\Http\Response
     */
    public function destroy(Election $election)
    {
        //
        $election->delete();
        return redirect()->route('elections.index')->with('success','Election Succesfully Deleted');
    }
}

resources/views/election/create.blade.php
@extends('layouts.admin')

@section('main-content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ __('Add Election') }}</h1>

    @if (session('success'))
        <div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('status'))
        <div class="alert alert-success border-left-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-7 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"> Add Election</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('elections.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="election_name">Election Name</label>
                            <input type="text" id="election_name" name="election_name" placeholder="Enter Election Name"
                                class="form-control  {{ $errors->has('election_name') ? 'is-invalid' : '' }}">
                            @error('election_name')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="election_start_at">Start At</label>
                            <input type="datetime-local" class="form-control  {{ $errors->has('election_start_at') ? 'is-invalid' : '' }}" id="election_start_at"
                                name="election_start_at" placeholder="Start date">
                            @error('election_start_at')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="faculty">End At</label>
                            <input type="datetime-local" name="election_end_at" id="election_end_at" class="form-control  {{ $errors->has('election_end_at') ? 'is-invalid' : '' }}"
                                placeholder="End Date">
                            @error('election_end_at')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/election/edit.blade.php
@extends('layouts.admin')

@section('main-content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ __('Edit Election') }}</h1>

    @if (session('success'))
        <div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    {{-- @if ($errors->any())
        <div class="alert alert-danger border-left-danger alert-dismissible fade show" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif --}}


    @if (session('status'))
        <div class="alert alert-success border-left-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-7 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"> Edit Election</h6>
                </div>
                <div class="card-body">
                    <form action="{{ route('elections.update', $data['election']->id) }}" method="POST">
                        @csrf
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group">
                            <label for="election_name">Election Name</label>
                            <input type="text"  id="election_name" name="election_name" class="form-control {{ $errors->has('election_name') ? 'is-invalid' : '' }}"
                                 value="{{ $data['election']->name }}"
                                placeholder="Enter Election Name">
                            @error('election_name')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror

                        </div>
                        <div class="form-group">
                            <label for="election_start_at">Start At</label>
                            <input type="text" id="election_start_at" name="election_start_at"
                                class="form-control datetimepicker {{ $errors->has('election_start_at') ? 'is-invalid' : '' }}"
                                value="{{ date('d-m-Y H:i', strtotime($data['election']->start_at)) }}"
                                placeholder="Start date">
                            @error('election_start_at')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="faculty">End At</label>
                            <input type="text" name="election_end_at" id="election_end_at"
                                class="form-control datetimepicker {{ $errors->has('election_end_at') ? 'is-invalid' : '' }} "
                                value="{{ date('d-m-Y H:i', strtotime($data['election']->end_at)) }}"
                                placeholder="End Date">
                            @error('election_end_at')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror

                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        @push('scripts')
            <script>
                var config = {
                    enableTime: true,
                    dateFormat: "d-m-Y H:i",
                    // minDate: "today",
                };

                $('.datetimepicker').flatpickr(config);
            </script>
        @endpush

    </div>
@endsection

resources/views/election/index.blade.php
@extends('layouts.admin')

@section('main-content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ __('Election') }}</h1>

    @if (session('success'))
        <div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    @if (session('status'))
        <div class="alert alert-success border-left-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-12 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col align-self-start">
                            <h6 class="m-0 font-weight-bold text-primary">Election</h6>
                        </div>
                        <div class="col align-self-end"><a href="{{ route('elections.create') }}" class="btn btn-success btn-sm float-right">Add Election</a></div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table Mydatatable">
                        <thead>
                            <th>Name</th>
                            <th>Start at</th>
                            <th>End at</th>
                            <th>Status</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @php
                                use Carbon\Carbon;
                            @endphp

                            @foreach ($elections as $election)
                                <tr>
                                    <td>{{ $election->name }}</td>
                                    <td>{{ $election->start_at }}</td>
                                    <td>{{ $election->end_at }}</td>
                                    <td>
                                        @php
                                            if (date('Y-m-d H:i:s') > $election->end_at) {
                                                echo "Ended";
                                            } else if( ( date('Y-m-d H:i:s')) > $election->start_at){
                                                echo "Started";
                                            }else{
                                                echo "Pending";
                                            }
                                        @endphp

                                    </td>
                                    <td>
                                        <div class="row">
                                            <a href="{{ route('elections.edit', $election->id) }}" class="text-info"><i
                                                    class="fas fa-cog"></i></a>
                                            &nbsp;&nbsp;
                                            <a href="{{ route('candidates.index', $election->id) }}" class="text-primary">
                                                <i class="fas fa-eye"></i></a>
                                            &nbsp;&nbsp;
                                            <a href="" class="text-success"><i class="fas fa-rocket"></i></a>
                                            &nbsp;&nbsp;
                                            <a href="" class="text-warning"><i class="fas fa-poll"></i></a>
                                            &nbsp;&nbsp;
                                            <form action="{{ route('elections.destroy', $election->id) }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn p-0">
                                                    <div class="text-danger"><i class="fas fa-trash"></div></i>
                                                </button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>


        </div>


    </div>
@endsection